---
- name: Install gnupg
  ansible.builtin.apt:
    name: "gnupg"
    update_cache: yes
    state: present

- name:
  ansible.builtin.get_url:
    url: https://public.fusiondirectory.org/FD-archive-key
    dest: /tmp/FD-archive-key

- name: Add Apt signing key
  ansible.builtin.apt_key:
    file: /tmp/FD-archive-key
    state: present

- name: Add FusionDirectory repository
  ansible.builtin.apt_repository:
    repo: deb https://public.fusiondirectory.org/stretch-fusiondirectory-release/ stretch main
    filename: fusiondirectory-release.list
  when: not fd_entreprise_setup

- name: Create FusionDirectory Entreprise Auth configuration
  ansible.builtin.template:
    src: "{{ fd_entreprise_auth_template }}"
    dest: "/etc/apt/{{ fd_entreprise_auth_filename }}"
    mode: 0644
    owner: root
    group: root
  when: fd_entreprise_setup

- name: Add FusionDirectory entreprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.fusiondirectory.org/buster-fusiondirectory-dev buster main
    filename: fusiondirectory-entreprise-release.list
  when: fd_entreprise_setup

- name: Add schema2ldif repository
  ansible.builtin.apt_repository:
    repo: deb https://public.fusiondirectory.org/stretch-schema2ldif-release/ stretch main
    filename: schema2ldif-release.list

- name: Install fusion directory and other dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ fd_packages }}"

- name: Create FusionDirectory configuration
  ansible.builtin.template:
    src: fusiondirectory.conf.j2
    dest: /etc/fusiondirectory/fusiondirectory.conf
    mode: 0644
    owner: root
    group: root

- name: Copy apache vhosts configuration.
  ansible.builtin.template:
    src: "{{ fd_apache_vhosts_template }}"
    dest: "/etc/apache2/sites-available/{{ fd_apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: fd_apache_update_vhosts
