---
- name: Install gnupg
  ansible.builtin.apt:
    name: "gnupg"
    update_cache: yes
    state: present

- name:
  ansible.builtin.get_url:
    url: https://public.fusiondirectory.org/FD-archive-key
    dest: /tmp/FD-archive-key

- name: Add Apt signing key
  ansible.builtin.apt_key:
    file: /tmp/FD-archive-key
    state: present

- name: Add FusionDirectory repository
  ansible.builtin.apt_repository:
    repo: deb https://public.fusiondirectory.org/stretch-fusiondirectory-release/ stretch main
    filename: fusiondirectory-release.list

- name: Add schema2ldif repository
  ansible.builtin.apt_repository:
    repo: deb https://public.fusiondirectory.org/stretch-schema2ldif-release/ stretch main
    filename: schema2ldif-release.list

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ fd_packages }}"

- name: Create FusionDirectory configuration
  ansible.builtin.template:
    src: fusiondirectory.conf.j2
    dest: /etc/fusiondirectory/fusiondirectory.conf
    mode: 0640
    owner: root
    group: root
